### ISSUE TITLE
ngentest is not working when working with ngrx store pattern

### ISSUE THREAD

**Issue by AkshayKatta** [allenhwkim/ngentest#12] opened 2019-04-18 02:11 UTC
I am using ngrx architecture for my project. If i try to generate autogenrated test cases using ngentest , it gives me error 
```
node:18676) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at forEach.param (C:\Users\akatta\AppData\Roaming\npm\node_modules\ngentest\src\get-directive-data.js:86:26)
    at Array.forEach (<anonymous>)
    at getDirectiveData (C:\Users\akatta\AppData\Roaming\npm\node_modules\ngentest\src\get-directive-data.js:53:43)
    at parseTypescript.then.tsParsed (C:\Users\akatta\AppData\Roaming\npm\node_modules\ngentest\index.js:44:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:865:11)
    at internal/main/run_main_module.js:21:11
(node:18676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by allenhwkim** [comment] 2019-04-29 17:49
Can you provide an example with @ngrx?
Currently I don't have an intention to exclusively support @ngrx.
However, if the implementation is easy, there is no reason not to do it.

**Comment by Butterbluemchen** [comment] 2019-07-08 12:13
I think the Problem is that generics are not handled yet.
When using something like ElementRef<HTMLElement>, the exception will be thrown.
The importLib variable is undefined in my case. I added "importLib && " as a workaround.

The following import will be generated:
import {ElementRef<HTMLElement>} from 'undefined';

You can support NGRX with the following code:

import { provideMockStore } from '@ngrx/store/testing';
describe('TestComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        provideMockStore({/*STORE*/})
      ]
    }).compileComponents();
  });

**Comment by allenhwkim** [comment] 2023-11-15 22:09
Closing this because it's not possible to replicate error without a source code.

**Closed by allenhwkim** 2023-11-15 22:09 UTC
Labels: enhancement
